//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDBEntities : DbContext
    {
        public HospitalDBEntities()
            : base("name=HospitalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cita> tb_cita { get; set; }
        public virtual DbSet<tb_doctor> tb_doctor { get; set; }
        public virtual DbSet<tb_especialidad> tb_especialidad { get; set; }
        public virtual DbSet<tb_paciente> tb_paciente { get; set; }
        public virtual DbSet<tb_tipo_cita> tb_tipo_cita { get; set; }
        public virtual DbSet<tb_tipo_documento> tb_tipo_documento { get; set; }
    }
}
